[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"

[project]
name = "rag-starterkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chonkie>=1.5.2",
    "diskcache>=5.6.3",
    "fastembed>=0.7.4",
    "llama-cloud-services>=0.6.88",
    "openai>=2.14.0",
    "qdrant-client>=1.16.2",
    "typer>=0.20.0",
]

[tool.uv.build-backend]
module-name = "rag_starterkit"
